language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - export BOTO_CONFIG=/dev/null
install:
  - make requirements-dev
script:
  - PYTEST_ARGS='--cov=app --cov-report=term-missing' make test
notifications:
  email: false
